/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/planted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_planted"];
        put?: never;
        post: operations["write_planted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** PlantedResponse */
        PlantedResponse: {
            /** Kept */
            kept: string;
            /** Placeholder */
            placeholder: null;
            /**
             * Enumeratednull
             * @enum {unknown}
             */
            enumeratedNull: null;
            /** Arrayofnull */
            arrayOfNull: null[];
            nullableObject: components["schemas"]["NestedResponse"] | null;
            nested: components["schemas"]["NestedResponse"];
        };
        /** NestedResponse */
        NestedResponse: {
            /** Held */
            held: number;
            /** Buried */
            buried: null;
        };
        /** PlantedRequest */
        PlantedRequest: {
            /** Sent */
            sent: string;
            /** Unsendable */
            unsendable: null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_planted: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantedResponse"];
                };
            };
        };
    };
    write_planted: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantedRequest"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
