"""Detecting the overlaps a calendar sync just created, against the live plan, at ingest time.

A conflict is detected when the commitment arrives rather than discovered later by a solve, and that
ordering is the whole reason the notice can name the specific block affected. A solve would answer
minutes later at best, and its answer would be a plan rather than a question.

```
for each ISO week overlapping the projection horizon:
  live plan?                        no  ──▶ nothing to collide with
  yes ──▶ read the commitments that can cast into the week, and what their types cast
      ──▶ detect: a commitment over a planned block, a buffer over a PINNED block
      ──▶ raise each one not already asked about
```

## Which weeks are read, and why the horizon is the bound

A conflict is about a block, so only a week that holds a live plan can hold one, and only a week
inside the projection horizon is kept supplied with one. The horizon is the same derivation the plan
horizon maintainer uses, from the same two facts: today's local date in the home zone, and the write
target's own length. A week further out holds no plan yet, so reading it would cost a query to
answer "nothing", and a week already past is one no resolution could act on.

## The commitments are read the way an assembly reads them

The span read is widened by what the tenant's own types can cast, because a Monday-morning exam
casts its prep into the Sunday evening of the week before. The shadows are then generated by the
same generator a solve reads, so what is detected against is the geometry the plan will hold rather
than a second reading of it.

**Off-plan spans suppress nothing here.** A commitment during a period the user declared off is
still a commitment, and a pinned block inside one is still the user's own edit, so the collision is
raised: off-plan suspends syncr's scheduling, not the world's.

## Cost, and why it is paid only when something moved

One revision read, one anchor read and one type read per horizon week, plus one read of the zone
profile per pass, and the caller only asks after a pass that created or updated a commitment. A poll
that found nothing new, a feed that answered "unchanged", and a feed that could not be read all cost
nothing at all.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from syncr_api.anchors.reach import casting_span
from syncr_api.anchors.repository import AnchorRepository
from syncr_api.anchors.shadows import regenerate
from syncr_api.anchors.type_repository import AnchorTypeRepository
from syncr_api.calendars.horizons import read_horizon_days
from syncr_api.calendars.repository import CalendarSourceRepository
from syncr_api.horizon.weeks import horizon_weeks
from syncr_api.plans.calendar_occupancy import typed_anchors
from syncr_api.plans.conflicts import PlanConflictRepository
from syncr_api.plans.overlaps import detected_conflicts
from syncr_api.plans.repository import PlanRepository
from syncr_api.plans.stored_documents import plan_document
from syncr_api.user_settings.repository import SettingsRepository, TravelOverrideRepository
from syncr_api.user_settings.zone_reading import as_domain, local_date, zone_profile
from syncr_common.logging import get_logger
from syncr_common.metrics import measured
from syncr_domain.weeks import week_span
from syncr_solver.inputs import Anchor, ShadowBlock

if TYPE_CHECKING:
    from datetime import datetime

    from sqlalchemy.ext.asyncio import AsyncSession

    from syncr_api.plans.records import ConflictRecord
    from syncr_domain.identifiers import TenantId
    from syncr_domain.intervals import Interval
    from syncr_domain.plan import PlanDocument
    from syncr_domain.weeks import IsoWeek
    from syncr_domain.zones import ZoneProfile

_log = get_logger("syncr.conflicts")


@dataclass(frozen=True, slots=True)
class Arriving:
    """What one week's commitments put in it: the commitments, and the buffers they cast.

    The two shapes an assembly resolves them into, so the detector reads what a solve will read
    rather than a projection made for this call.
    """

    anchors: tuple[Anchor, ...] = ()
    derived: tuple[ShadowBlock, ...] = ()


class IngestConflicts:
    """Raises the conflicts one tenant's live plans hold, after their commitments changed."""

    def __init__(self, session: AsyncSession, tenant_id: TenantId) -> None:
        self._session = session
        self._tenant_id = tenant_id

    @measured("conflicts")
    async def detect(self, *, now: datetime) -> tuple[ConflictRecord, ...]:
        """Every conflict raised by this pass, over every horizon week that holds a plan.

        Answers with what was newly raised rather than with every overlap that exists, because the
        notice this feeds is the only one this product sends and a repeat is not news.
        """
        settings = await SettingsRepository(self._session, self._tenant_id).read()
        overrides = await TravelOverrideRepository(self._session, self._tenant_id).list_all()
        profile = zone_profile(settings.home_zone, as_domain(overrides))
        weeks = horizon_weeks(
            today=local_date(now, settings.home_zone),
            horizon_days=await read_horizon_days(
                CalendarSourceRepository(self._session, self._tenant_id)
            ),
        )
        raised: list[ConflictRecord] = []
        for week in weeks:
            raised.extend(await self._detected(week, profile=profile, now=now))
        if raised:
            _log.info(
                "conflicts.ingest.raised",
                tenant_id=str(self._tenant_id),
                horizon_weeks=len(weeks),
                conflicts_raised=len(raised),
            )
        return tuple(raised)

    async def _detected(
        self, week: IsoWeek, *, profile: ZoneProfile, now: datetime
    ) -> tuple[ConflictRecord, ...]:
        """One week's conflicts, or nothing when the week holds no plan to collide with."""
        live = await self._live(week)
        if live is None:
            return ()
        arriving = await self._arriving(week_span(week, profile))
        found = detected_conflicts(
            live, anchors=arriving.anchors, derived=arriving.derived, now=now
        )
        conflicts = PlanConflictRepository(self._session, self._tenant_id)
        return await conflicts.raise_all(found, at=now)

    async def _live(self, week: IsoWeek) -> PlanDocument | None:
        latest = await PlanRepository(self._session, self._tenant_id).latest(week)
        return None if latest is None else plan_document(latest.document)

    async def _arriving(self, span: Interval) -> Arriving:
        """The commitments ``span`` holds and the buffers the tenant's types cast into it.

        The types are read first, which is the cheaper order rather than a safe one, and the pairing
        treats a commitment carrying a type this read did not see as opaque busy time: that race is
        answered by the version bump the pass performs rather than by failing the detection.
        """
        types = await AnchorTypeRepository(self._session, self._tenant_id).list_all()
        loaded = await AnchorRepository(self._session, self._tenant_id).overlapping(
            casting_span(span, tuple(row.specification for row in types))
        )
        paired = typed_anchors(loaded, types)
        cast = regenerate(paired)
        return Arriving(
            anchors=tuple(
                Anchor(
                    anchor_id=pair.anchor.id,
                    interval=pair.anchor.interval,
                    title=pair.anchor.title,
                )
                for pair in paired
                if pair.anchor.interval.overlaps(span)
            ),
            derived=tuple(
                ShadowBlock(
                    binding=block.binding,
                    interval=block.interval,
                    area_id=block.area_id,
                    title=block.title,
                )
                for block in cast.blocks
                if block.interval.overlaps(span)
            ),
        )
