"""Models and a SQL recorder the tenancy boundary tests are stated against.

Two models in a metadata of their own: one that follows every tenancy rule and one that
breaks all of them. They exist because the rules apply to tables that mostly do not
exist yet, so without a deliberately broken subject each rule would pass on an empty
schema and go on passing after the first real violation arrives.

They are kept out of ``Base.metadata`` on purpose. A control model attached to the
application's metadata would appear in the next autogenerated migration.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from sqlalchemy import DateTime, Index, MetaData, String, event
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from syncr_api.accounts.models import Tenant
from syncr_api.core.tenancy import TENANT_ID_COLUMN, TenantScoped

if TYPE_CHECKING:
    from collections.abc import Iterator

    from sqlalchemy.engine import Connection
    from sqlalchemy.ext.asyncio import AsyncEngine

# Statements a recorder ignores: the driver's own bookkeeping and the schema setup a test
# does to create its own table.
_STATEMENT_NOISE = ("BEGIN", "COMMIT", "ROLLBACK", "CREATE ", "DROP ", "SELECT 1")


class ControlBase(DeclarativeBase):
    """A metadata of its own, so a control model never reaches a real migration."""

    metadata = MetaData()


# The scoped mixin's foreign key targets `tenants`, and SQLAlchemy resolves a foreign key
# against the metadata the referencing table is in, so the DDL for a control table cannot
# be generated without a definition of `tenants` here. Borrowed rather than redeclared:
# a second hand-written definition of the same table would be free to drift from the one
# the migration creates.
Tenant.__table__.to_metadata(ControlBase.metadata)

CONTROL_TABLES = frozenset({"scoped_things", "unscoped_things"})


class ScopedThing(ControlBase, TenantScoped):
    """A correctly scoped table, standing in for the first real one.

    Also the only current exercise of the scoped mixin: none of the three identity
    tables uses it, so without this the mixin would be unproven until plan storage
    lands, and a mixin that cannot map is a failure at import.
    """

    __tablename__ = "scoped_things"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_scoped_things_tenant_id_recorded_at", TENANT_ID_COLUMN, "recorded_at"),
    )


class UnscopedThing(ControlBase):
    """A table that forgot the scope, and names a user instead."""

    __tablename__ = "unscoped_things"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(nullable=False)
    label: Mapped[str] = mapped_column(String(20))

    __table_args__ = (Index("ix_unscoped_things_label_id", "label", "id"),)


class StatementRecorder:
    """Records the SQL a database actually executed, for the runtime tenancy rule.

    Compiling a statement proves what a repository built. This proves what reached
    Postgres, which is the claim the rule is about: a statement assembled correctly and
    then modified downstream would pass the first check and fail this one.
    """

    def __init__(self) -> None:
        self.statements: list[str] = []

    def against(self, table: str) -> list[str]:
        """Every recorded statement that reads or writes ``table``."""
        return [statement for statement in self.statements if table in statement]

    def without_a_tenant_predicate(self, table: str) -> list[str]:
        """Statements against ``table`` that carry no tenant predicate."""
        return [
            statement
            for statement in self.against(table)
            if f"{table}.{TENANT_ID_COLUMN} =" not in statement
            and f"{TENANT_ID_COLUMN} =" not in statement
        ]

    def record(
        self,
        _connection: Connection,
        _cursor: object,
        statement: str,
        _parameters: object,
        _context: object,
        _executemany: bool,
    ) -> None:
        """The ``before_cursor_execute`` listener. Called by SQLAlchemy, not by a test."""
        collapsed = " ".join(statement.split())
        if not collapsed.startswith(_STATEMENT_NOISE):
            self.statements.append(collapsed)


def recording(engine: AsyncEngine) -> Iterator[StatementRecorder]:
    """Attach a recorder to ``engine`` for the duration of a test."""
    recorder = StatementRecorder()
    event.listen(engine.sync_engine, "before_cursor_execute", recorder.record)
    try:
        yield recorder
    finally:
        event.remove(engine.sync_engine, "before_cursor_execute", recorder.record)
