"""The ``areas`` table as a migrated database holds it, against the model that describes it.

Two statements a request-level test cannot make. The first is a drift check in both directions:
the columns the chain leaves behind are exactly the columns the model declares, so a column added
to one and not the other is visible here rather than in an autogenerated revision nobody expected.
The second names the field this table deliberately does not hold, because the absence is a decision
rather than an omission: a preference names its own owner, so ``preferences`` is where that relation
lives and an Area holds no identifier for it.

The equality is what makes both non-vacuous. An empty reflection, a misspelled table or a database
the chain never reached fails it rather than passing over nothing.
"""

from __future__ import annotations

import pytest
from sqlalchemy import inspect as sa_inspect

from syncr_api.areas.config import AREAS_TABLE
from syncr_api.areas.models import AreaRow
from syncr_api.core.db import create_database
from tests.live_tenants import run

pytestmark = pytest.mark.integration

# The column an Area does not hold. A preference names its own owner, so the relation lives on the
# preference rather than in a second place here.
PREFERENCE_IDENTIFIER_COLUMN = "default_preference_id"


def migrated_columns(database_url: str, table: str) -> set[str]:
    """The column names Postgres reports for one table, read on a connection of this test's own."""

    async def read() -> set[str]:
        database = create_database(database_url)
        try:
            async with database.engine.connect() as connection:
                return await connection.run_sync(
                    lambda sync: {column["name"] for column in sa_inspect(sync).get_columns(table)}
                )
        finally:
            await database.engine.dispose()

    return run(read())


def test_the_migrated_table_holds_exactly_the_columns_the_model_declares(
    live_database_url: str,
) -> None:
    declared = {column.name for column in AreaRow.__table__.columns}

    assert migrated_columns(live_database_url, AREAS_TABLE) == declared


def test_no_column_of_the_table_names_a_preference(live_database_url: str) -> None:
    migrated = migrated_columns(live_database_url, AREAS_TABLE)

    # The control: the reflection reached a table with columns in it, so the absence below is a
    # statement about this table rather than about an empty read.
    assert "floor_hours" in migrated
    assert PREFERENCE_IDENTIFIER_COLUMN not in migrated
