"""The tenancy rules as Postgres sees them, not as a compiler renders them.

Compiling a statement proves what a repository built. This proves three things a
compilation cannot: that the statement Postgres executed still carried the predicate,
that the rows it returned were only the scoped tenant's, and that the schema rejects a
second user in a tenant rather than merely being expected not to receive one.

The scoped table is created and dropped by this module, in a Postgres schema of its own for
the run. It has to be a real table for the statement to execute, and it must not be in
``Base.metadata``, or it would appear in the next autogenerated migration. Plan storage brings
the first production table under these rules; until then this is what keeps them exercised
rather than merely written.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING
from uuid import uuid4

import pytest
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from syncr_api.accounts.models import Tenant, User
from syncr_api.accounts.passwords import hash_password
from syncr_api.accounts.repository import UserRepository
from syncr_api.core.clock import utc_now
from syncr_api.core.db import create_sessionmaker
from syncr_api.core.repository import TenantScopedRepository
from syncr_api.core.tenancy import TENANT_ID_COLUMN
from tests.control_models import CONTROL_TABLES, ControlBase, ScopedThing, recording, table_of
from tests.control_schema import create_engine_in_schema, run_schema

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Iterator

    from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession

    from syncr_domain.identifiers import TenantId
    from tests.control_models import StatementRecorder

pytestmark = pytest.mark.integration

PASSWORD = "correct-horse-battery-staple"  # pragma: allowlist secret


@pytest.fixture(scope="session")
def control_schema(live_database_url: str) -> Iterator[str]:
    """The schema this run's control tables live in, dropped when the run ends."""
    with run_schema(live_database_url) as schema:
        yield schema


@pytest.fixture
async def engine(live_database_url: str, control_schema: str) -> AsyncIterator[AsyncEngine]:
    """An engine owned by this test's own event loop, scoped to the run's schema."""
    live = create_engine_in_schema(live_database_url, control_schema)
    yield live
    await live.dispose()


@pytest.fixture
async def scoped_table(engine: AsyncEngine) -> AsyncIterator[None]:
    """Create the control table for one test, and drop it afterwards.

    Created in the run's own schema, whose search path falls through to the shared one, so its
    foreign key still points at the real ``tenants`` table: a row with an invented tenant is
    rejected here exactly as it would be in production.
    """
    table = table_of(ScopedThing)
    async with engine.begin() as connection:
        await connection.run_sync(table.create)
    yield
    async with engine.begin() as connection:
        await connection.run_sync(table.drop)


@pytest.fixture
async def session(engine: AsyncEngine, scoped_table: None) -> AsyncIterator[AsyncSession]:
    """A session against the live database, with the control table present."""
    assert scoped_table is None
    factory = create_sessionmaker(engine)
    async with factory() as opened:
        yield opened
        await opened.rollback()


@pytest.fixture
async def two_tenants(session: AsyncSession) -> list[TenantId]:
    """Two real tenant rows, so a scoped read has another tenant's rows to not return."""
    tenants = [Tenant(id=uuid4(), created_at=utc_now()) for _ in range(2)]
    session.add_all(tenants)
    await session.flush()
    return [tenant.id for tenant in tenants]


@pytest.fixture
def recorder(engine: AsyncEngine) -> Iterator[StatementRecorder]:
    """Records every statement this test's engine executes."""
    yield from recording(engine)


async def insert_row(session: AsyncSession, tenant_id: TenantId) -> ScopedThing:
    row = ScopedThing(id=uuid4(), tenant_id=tenant_id, recorded_at=datetime.now(UTC))
    session.add(row)
    await session.flush()
    return row


async def test_a_scoped_read_returns_only_the_repositorys_own_tenant(
    session: AsyncSession, two_tenants: list[TenantId]
) -> None:
    mine, theirs = two_tenants
    await insert_row(session, mine)
    await insert_row(session, theirs)
    repository = TenantScopedRepository(session, mine)

    found = list(await session.scalars(repository.scoped_select(ScopedThing)))

    assert [row.tenant_id for row in found] == [mine]


async def test_the_statement_postgres_executed_carried_the_tenant_predicate(
    session: AsyncSession, two_tenants: list[TenantId], recorder: StatementRecorder
) -> None:
    repository = TenantScopedRepository(session, two_tenants[0])

    await session.scalars(repository.scoped_select(ScopedThing))

    assert recorder.against(ScopedThing.__tablename__), "no statement reached the database"
    assert recorder.without_a_tenant_predicate(ScopedThing.__tablename__) == []


async def test_the_recorder_reports_a_statement_that_reached_postgres_unscoped(
    session: AsyncSession, recorder: StatementRecorder
) -> None:
    # The control. Without it, "every executed statement was scoped" would also hold on a
    # run where nothing was executed or where the reading was wrong.
    await session.scalars(select(ScopedThing))

    unscoped = recorder.without_a_tenant_predicate(ScopedThing.__tablename__)

    assert len(unscoped) == 1, recorder.statements


async def test_the_scoped_column_is_not_nullable_in_the_live_schema(
    session: AsyncSession,
) -> None:
    # The mixin declares it non-null; this is the database agreeing.
    session.add(ScopedThing(id=uuid4(), recorded_at=datetime.now(UTC)))

    with pytest.raises(IntegrityError):
        await session.flush()


async def test_a_scoped_row_cannot_name_a_tenant_that_does_not_exist(
    session: AsyncSession,
) -> None:
    # The mixin's foreign key, doing its job: a scope is a real tenant or it is nothing.
    with pytest.raises(IntegrityError):
        await insert_row(session, uuid4())


def test_no_control_table_is_in_the_applications_metadata() -> None:
    from syncr_api.core.orm import Base

    # `tenants` is deliberately present in both, borrowed so the control table's foreign
    # key resolves. What must never appear in the application's metadata is a control
    # table itself, because it would then appear in the next autogenerated migration.
    assert CONTROL_TABLES & set(Base.metadata.tables) == set()
    assert set(ControlBase.metadata.tables) >= CONTROL_TABLES


# --- The schema's own enforcement of one user per tenant ------------------------


async def test_a_second_user_in_one_tenant_is_rejected_by_the_database(
    engine: AsyncEngine,
) -> None:
    # The invariant every later table depends on: a tenant holds exactly one user, so no
    # plan row needs a user dimension. It has to be the unique index that rejects this,
    # not a check in a service, because a service can be bypassed by the next caller.
    factory = create_sessionmaker(engine)
    async with factory() as session:
        created = await UserRepository(session).create_tenant_with_user(
            email=f"first-{uuid4().hex}@syncr.test",
            password_hash=hash_password(PASSWORD),
            created_at=utc_now(),
        )
        session.add(
            User(
                id=uuid4(),
                tenant_id=created.tenant_id,
                email=f"second-{uuid4().hex}@syncr.test",
                password_hash=hash_password(PASSWORD),
                created_at=utc_now(),
            )
        )
        with pytest.raises(IntegrityError):
            await session.flush()
        await session.rollback()


async def test_one_email_cannot_be_registered_twice(engine: AsyncEngine) -> None:
    # Sign-in resolves a user by email before any tenant is known, so a duplicate email
    # would make "which account is this" unanswerable.
    email = f"owner-{uuid4().hex}@syncr.test"
    factory = create_sessionmaker(engine)
    async with factory() as session:
        users = UserRepository(session)
        await users.create_tenant_with_user(
            email=email, password_hash=hash_password(PASSWORD), created_at=utc_now()
        )
        with pytest.raises(IntegrityError):
            await users.create_tenant_with_user(
                email=email, password_hash=hash_password(PASSWORD), created_at=utc_now()
            )
        await session.rollback()


async def test_the_stored_user_row_carries_its_tenant(engine: AsyncEngine) -> None:
    factory = create_sessionmaker(engine)
    async with factory() as session:
        created = await UserRepository(session).create_tenant_with_user(
            email=f"owner-{uuid4().hex}@syncr.test",
            password_hash=hash_password(PASSWORD),
            created_at=utc_now(),
        )
        found = await session.scalar(select(User).where(User.id == created.id))
        assert found is not None
        stored_tenant_id = getattr(found, TENANT_ID_COLUMN)
        await session.rollback()

    assert stored_tenant_id == created.tenant_id
